import Head from 'next/head'
import { GiTakeMyMoney } from "react-icons/gi"
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-w-full min-h-screen bg-slate-100'>
        
        <div className='container max-w-lg h-full pt-12 mx-auto'>
          <h3 className='text-2xl text-gray-900 text-center py-5'>Welcome to Family Member Asset App</h3>
          <div className='w-[500px] h-[200px] rounded-lg flex flex-col gap-4 justify-center items-center bg-gray-900'>
            <div>
              <p className='text-white text-lg'>Please choose your menu</p>
            </div>
            <div className='flex gap-5 justify-center items-center'>
              <Link href={'/asset-records'} 
              className='flex flex-col items-center text-black outline outline-1 outline-white rounded-lg bg-slate-200 p-2'>
                <GiTakeMyMoney className='w-[70px] h-[70px]' /> 
                <p>Asset</p>               
              </Link>
              <Link href={'/member'} 
              className='flex flex-col items-center text-black outline outline-1 outline-white rounded-lg bg-slate-200 p-2'>
                <GiTakeMyMoney className='w-[70px] h-[70px]' /> 
                <p>Member</p>               
              </Link>
              <Link href={'/family-asset'} className='flex flex-col items-center text-black outline outline-1 outline-white rounded-lg bg-slate-200 p-2'>
                <GiTakeMyMoney className='w-[70px] h-[70px]' /> 
                <p>Familiy Member Asset</p>               
              </Link>
            </div>              
          </div>            
        </div>        
      </main>
    </>
  )
}
